<a href="https://colab.research.google.com/github/July230/CopyCode/blob/develop/LecturaDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerías

In [ ]:
import numpy as np
import pandas as pd
import io
import os
import re
import tensorflow as tf
from collections import Counter, defaultdict
from google.colab import files
from concurrent.futures import ThreadPoolExecutor
from transformers import BertTokenizer, BertModel
from t.text import BertTokenizer

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Dataframes

In [ ]:
parent_directory = "/content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio"
dataset_directory = os.path.join(parent_directory, "dataset")

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipykernel_3096/2135108706.py:1: SyntaxWarning: invalid escape sequence '\ '
  parent_directory = "/content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio"

In [ ]:
%cd {dataset_directory}
%ls

/content/drive/.shortcut-targets-by-id/1Xut7nWIe-55SLuAofdhgyG3ekr1fIvsa/IA y Compiladores/Reto_plagio/dataset
checkpoint_m1/  dev/     test/                train/     train_source.parquet
dataset/        dev.csv  tokens_official.csv  train.csv  unlabeled_test.csv

In [ ]:
df_train = pd.read_csv("./train.csv")

In [ ]:
df_validation = pd.read_csv("./dev.csv")

In [ ]:
df_test = pd.read_csv("./unlabeled_test.csv")

In [ ]:
df_all = pd.concat([df_train, df_validation, df_test])

In [ ]:
df_all

         uid    pid
0      415.0  27909
1      415.0  55938
2      415.0  90936
3      415.0  56858
4      415.0   9447
...      ...    ...
24995    NaN  54090
24996    NaN  62563
24997    NaN  45920
24998    NaN  81447
24999    NaN  94031

[100000 rows x 2 columns]

# Convertir archivos a dataframe

In [ ]:
def build_source_dataframe(path, metadata_df):
  """
  Copies the source code to a column of a dataframe

  Parameters
  ----------

  """
  records = []

  for idx, row in enumerate(metadata_df.itertuples(index=False)):

      pid = str(row.pid)

      file_path = os.path.join(path, pid)

      try:
          with open(file_path, "r", encoding="utf-8") as file:
              source_code = file.read()

          records.append({
              "uid": row.uid,
              "pid": pid,
              "source_code": source_code,
              "num_chars": len(source_code),
              "num_lines": source_code.count("\n") + 1
          })

      except Exception as e:
          print(f"Error leyendo {pid}: {e}")

      if idx % 100 == 0:
          print(f"Procesados {idx} archivos")

  return pd.DataFrame(records)

In [ ]:
train_path = os.path.join(dataset_directory, "train")
dev_path = os.path.join(dataset_directory, "dev")
test_path = os.path.join(dataset_directory, "test")

## Train

In [ ]:
%ls {dataset_directory}

checkpoint_m1/  dev/     test/                train/     train_source.parquet
dataset/        dev.csv  tokens_official.csv  train.csv  unlabeled_test.csv

In [ ]:
"""
train_source = build_source_dataframe(
    path=train_path,
    metadata_df=df_train
)
"""

Procesados 0 archivos
Procesados 100 archivos
Procesados 200 archivos
Procesados 300 archivos
Procesados 400 archivos
Procesados 500 archivos
Procesados 600 archivos
Procesados 700 archivos
Procesados 800 archivos
Procesados 900 archivos
Procesados 1000 archivos
Procesados 1100 archivos
Procesados 1200 archivos
Procesados 1300 archivos
Procesados 1400 archivos
Procesados 1500 archivos
Procesados 1600 archivos
Procesados 1700 archivos
Procesados 1800 archivos
Procesados 1900 archivos
Procesados 2000 archivos
Procesados 2100 archivos
Procesados 2200 archivos
Procesados 2300 archivos
Procesados 2400 archivos
Procesados 2500 archivos
Procesados 2600 archivos
Procesados 2700 archivos
Procesados 2800 archivos
Procesados 2900 archivos
Procesados 3000 archivos
Procesados 3100 archivos
Procesados 3200 archivos
Procesados 3300 archivos
Procesados 3400 archivos
Procesados 3500 archivos
Procesados 3600 archivos
Procesados 3700 archivos
Procesados 3800 archivos
Procesados 3900 archivos
Procesados 4000 archivos
Procesados 4100 archivos
Procesados 4200 archivos
Procesados 4300 archivos
Procesados 4400 archivos
Procesados 4500 archivos
Procesados 4600 archivos
Procesados 4700 archivos
Procesados 4800 archivos
Procesados 4900 archivos
Procesados 5000 archivos
Procesados 5100 archivos
Procesados 5200 archivos
Procesados 5300 archivos
Procesados 5400 archivos
Procesados 5500 archivos
Procesados 5600 archivos
Procesados 5700 archivos
Procesados 5800 archivos
Procesados 5900 archivos
Procesados 6000 archivos
Procesados 6100 archivos
Procesados 6200 archivos
Procesados 6300 archivos
Procesados 6400 archivos
Procesados 6500 archivos
Procesados 6600 archivos
Procesados 6700 archivos
Procesados 6800 archivos
Procesados 6900 archivos
Procesados 7000 archivos
Procesados 7100 archivos
Procesados 7200 archivos
Procesados 7300 archivos
Procesados 7400 archivos
Procesados 7500 archivos
Procesados 7600 archivos
Procesados 7700 archivos
Procesados 7800 archivos
Procesados 7900 archivos
Procesados 8000 archivos
Procesados 8100 archivos
Procesados 8200 archivos
Procesados 8300 archivos
Procesados 8400 archivos
Procesados 8500 archivos
Procesados 8600 archivos
Procesados 8700 archivos
Procesados 8800 archivos
Procesados 8900 archivos
Procesados 9000 archivos
Procesados 9100 archivos
Procesados 9200 archivos
Procesados 9300 archivos
Procesados 9400 archivos
Procesados 9500 archivos
Procesados 9600 archivos
Procesados 9700 archivos
Procesados 9800 archivos
Procesados 9900 archivos
Procesados 10000 archivos
Procesados 10100 archivos
Procesados 10200 archivos
Procesados 10300 archivos
Procesados 10400 archivos
Procesados 10500 archivos
Procesados 10600 archivos
Procesados 10700 archivos
Procesados 10800 archivos
Procesados 10900 archivos
Procesados 11000 archivos
Procesados 11100 archivos
Procesados 11200 archivos
Procesados 11300 archivos
Procesados 11400 archivos
Procesados 11500 archivos
Procesados 11600 archivos
Procesados 11700 archivos
Procesados 11800 archivos
Procesados 11900 archivos
Procesados 12000 archivos
Procesados 12100 archivos
Procesados 12200 archivos
Procesados 12300 archivos
Procesados 12400 archivos
Procesados 12500 archivos
Procesados 12600 archivos
Procesados 12700 archivos
Procesados 12800 archivos
Procesados 12900 archivos
Procesados 13000 archivos
Procesados 13100 archivos
Procesados 13200 archivos
Procesados 13300 archivos
Procesados 13400 archivos
Procesados 13500 archivos
Procesados 13600 archivos
Procesados 13700 archivos
Procesados 13800 archivos
Procesados 13900 archivos
Procesados 14000 archivos
Procesados 14100 archivos
Procesados 14200 archivos
Procesados 14300 archivos
Procesados 14400 archivos
Procesados 14500 archivos
Procesados 14600 archivos
Procesados 14700 archivos
Procesados 14800 archivos
Procesados 14900 archivos
Procesados 15000 archivos
Procesados 15100 archivos
Procesados 15200 archivos
Procesados 15300 archivos
Procesados 15400 archivos
Procesados 15500 archivos
Procesados 15600 archivos
Procesados 15700 archivos
Procesados 15800 archivos
Procesados 15900 archivos
Procesados 16000 archivos
Procesados 16100 archivos
Procesados 16200 archivos
Procesados 16300 archivos
Procesados 16400 archivos
Procesados 16500 archivos
Procesados 16600 archivos
Procesados 16700 archivos
Procesados 16800 archivos
Procesados 16900 archivos
Procesados 17000 archivos
Procesados 17100 archivos
Procesados 17200 archivos
Procesados 17300 archivos
Procesados 17400 archivos
Procesados 17500 archivos
Procesados 17600 archivos
Procesados 17700 archivos
Procesados 17800 archivos
Procesados 17900 archivos
Procesados 18000 archivos
Procesados 18100 archivos
Procesados 18200 archivos
Procesados 18300 archivos
Procesados 18400 archivos
Procesados 18500 archivos
Procesados 18600 archivos
Procesados 18700 archivos
Procesados 18800 archivos
Procesados 18900 archivos
Procesados 19000 archivos
Procesados 19100 archivos
Procesados 19200 archivos
Procesados 19300 archivos
Procesados 19400 archivos
Procesados 19500 archivos
Procesados 19600 archivos
Procesados 19700 archivos
Procesados 19800 archivos
Procesados 19900 archivos
Procesados 20000 archivos
Procesados 20100 archivos
Procesados 20200 archivos
Procesados 20300 archivos
Procesados 20400 archivos
Procesados 20500 archivos
Procesados 20600 archivos
Procesados 20700 archivos
Procesados 20800 archivos
Procesados 20900 archivos
Procesados 21000 archivos
Procesados 21100 archivos
Procesados 21200 archivos
Procesados 21300 archivos
Procesados 21400 archivos
Procesados 21500 archivos
Procesados 21600 archivos
Procesados 21700 archivos
Procesados 21800 archivos
Procesados 21900 archivos
Procesados 22000 archivos
Procesados 22100 archivos
Procesados 22200 archivos
Procesados 22300 archivos
Procesados 22400 archivos
Procesados 22500 archivos
Procesados 22600 archivos
Procesados 22700 archivos
Procesados 22800 archivos
Procesados 22900 archivos
Procesados 23000 archivos
Procesados 23100 archivos
Procesados 23200 archivos
Procesados 23300 archivos
Procesados 23400 archivos
Procesados 23500 archivos
Procesados 23600 archivos
Procesados 23700 archivos
Procesados 23800 archivos
Procesados 23900 archivos
Procesados 24000 archivos
Procesados 24100 archivos
Procesados 24200 archivos
Procesados 24300 archivos
Procesados 24400 archivos
Procesados 24500 archivos
Procesados 24600 archivos
Procesados 24700 archivos
Procesados 24800 archivos
Procesados 24900 archivos
Procesados 25000 archivos
Procesados 25100 archivos
Procesados 25200 archivos
Procesados 25300 archivos
Procesados 25400 archivos
Procesados 25500 archivos
Procesados 25600 archivos
Procesados 25700 archivos
Procesados 25800 archivos
Procesados 25900 archivos
Procesados 26000 archivos
Procesados 26100 archivos
Procesados 26200 archivos
Procesados 26300 archivos
Procesados 26400 archivos
Procesados 26500 archivos
Procesados 26600 archivos
Procesados 26700 archivos
Procesados 26800 archivos
Procesados 26900 archivos
Procesados 27000 archivos
Procesados 27100 archivos
Procesados 27200 archivos
Procesados 27300 archivos
Procesados 27400 archivos
Procesados 27500 archivos
Procesados 27600 archivos
Procesados 27700 archivos
Procesados 27800 archivos
Procesados 27900 archivos
Procesados 28000 archivos
Procesados 28100 archivos
Procesados 28200 archivos
Procesados 28300 archivos
Procesados 28400 archivos
Procesados 28500 archivos
Procesados 28600 archivos
Procesados 28700 archivos
Procesados 28800 archivos
Procesados 28900 archivos
Procesados 29000 archivos
Procesados 29100 archivos
Procesados 29200 archivos
Procesados 29300 archivos
Procesados 29400 archivos
Procesados 29500 archivos
Procesados 29600 archivos
Procesados 29700 archivos
Procesados 29800 archivos
Procesados 29900 archivos
Procesados 30000 archivos
Procesados 30100 archivos
Procesados 30200 archivos
Procesados 30300 archivos
Procesados 30400 archivos
Procesados 30500 archivos
Procesados 30600 archivos
Procesados 30700 archivos
Procesados 30800 archivos
Procesados 30900 archivos
Procesados 31000 archivos
Procesados 31100 archivos
Procesados 31200 archivos
Procesados 31300 archivos
Procesados 31400 archivos
Procesados 31500 archivos
Procesados 31600 archivos
Procesados 31700 archivos
Procesados 31800 archivos
Procesados 31900 archivos
Procesados 32000 archivos
Procesados 32100 archivos
Procesados 32200 archivos
Procesados 32300 archivos
Procesados 32400 archivos
Procesados 32500 archivos
Procesados 32600 archivos
Procesados 32700 archivos
Procesados 32800 archivos
Procesados 32900 archivos
Procesados 33000 archivos
Procesados 33100 archivos
Procesados 33200 archivos
Procesados 33300 archivos
Procesados 33400 archivos
Procesados 33500 archivos
Procesados 33600 archivos
Procesados 33700 archivos
Procesados 33800 archivos
Procesados 33900 archivos
Procesados 34000 archivos
Procesados 34100 archivos
Procesados 34200 archivos
Procesados 34300 archivos
Procesados 34400 archivos
Procesados 34500 archivos
Procesados 34600 archivos
Procesados 34700 archivos
Procesados 34800 archivos
Procesados 34900 archivos
Procesados 35000 archivos
Procesados 35100 archivos
Procesados 35200 archivos
Procesados 35300 archivos
Procesados 35400 archivos
Procesados 35500 archivos
Procesados 35600 archivos
Procesados 35700 archivos
Procesados 35800 archivos
Procesados 35900 archivos
Procesados 36000 archivos
Procesados 36100 archivos
Procesados 36200 archivos
Procesados 36300 archivos
Procesados 36400 archivos
Procesados 36500 archivos
Procesados 36600 archivos
Procesados 36700 archivos
Procesados 36800 archivos
Procesados 36900 archivos
Procesados 37000 archivos
Procesados 37100 archivos
Procesados 37200 archivos
Procesados 37300 archivos
Procesados 37400 archivos
Procesados 37500 archivos
Procesados 37600 archivos
Procesados 37700 archivos
Procesados 37800 archivos
Procesados 37900 archivos
Procesados 38000 archivos
Procesados 38100 archivos
Procesados 38200 archivos
Procesados 38300 archivos
Procesados 38400 archivos
Procesados 38500 archivos
Procesados 38600 archivos
Procesados 38700 archivos
Procesados 38800 archivos
Procesados 38900 archivos
Procesados 39000 archivos
Procesados 39100 archivos
Procesados 39200 archivos
Procesados 39300 archivos
Procesados 39400 archivos
Procesados 39500 archivos
Procesados 39600 archivos
Procesados 39700 archivos
Procesados 39800 archivos
Procesados 39900 archivos
Procesados 40000 archivos
Procesados 40100 archivos
Procesados 40200 archivos
Procesados 40300 archivos
Procesados 40400 archivos
Procesados 40500 archivos
Procesados 40600 archivos
Procesados 40700 archivos
Procesados 40800 archivos
Procesados 40900 archivos
Procesados 41000 archivos
Procesados 41100 archivos
Procesados 41200 archivos
Procesados 41300 archivos
Procesados 41400 archivos
Procesados 41500 archivos
Procesados 41600 archivos
Procesados 41700 archivos
Procesados 41800 archivos
Procesados 41900 archivos
Procesados 42000 archivos
Procesados 42100 archivos
Procesados 42200 archivos
Procesados 42300 archivos
Procesados 42400 archivos
Procesados 42500 archivos
Procesados 42600 archivos
Procesados 42700 archivos
Procesados 42800 archivos
Procesados 42900 archivos
Procesados 43000 archivos
Procesados 43100 archivos
Procesados 43200 archivos
Procesados 43300 archivos
Procesados 43400 archivos
Procesados 43500 archivos
Procesados 43600 archivos
Procesados 43700 archivos
Procesados 43800 archivos
Procesados 43900 archivos
Procesados 44000 archivos
Procesados 44100 archivos
Procesados 44200 archivos
Procesados 44300 archivos
Procesados 44400 archivos
Procesados 44500 archivos
Procesados 44600 archivos
Procesados 44700 archivos
Procesados 44800 archivos
Procesados 44900 archivos
Procesados 45000 archivos
Procesados 45100 archivos
Procesados 45200 archivos
Procesados 45300 archivos
Procesados 45400 archivos
Procesados 45500 archivos
Procesados 45600 archivos
Procesados 45700 archivos
Procesados 45800 archivos
Procesados 45900 archivos
Procesados 46000 archivos
Procesados 46100 archivos
Procesados 46200 archivos
Procesados 46300 archivos
Procesados 46400 archivos
Procesados 46500 archivos
Procesados 46600 archivos
Procesados 46700 archivos
Procesados 46800 archivos
Procesados 46900 archivos
Procesados 47000 archivos
Procesados 47100 archivos
Procesados 47200 archivos
Procesados 47300 archivos
Procesados 47400 archivos
Procesados 47500 archivos
Procesados 47600 archivos
Procesados 47700 archivos
Procesados 47800 archivos
Procesados 47900 archivos
Procesados 48000 archivos
Procesados 48100 archivos
Procesados 48200 archivos
Procesados 48300 archivos
Procesados 48400 archivos
Procesados 48500 archivos
Procesados 48600 archivos
Procesados 48700 archivos
Procesados 48800 archivos
Procesados 48900 archivos
Procesados 49000 archivos
Procesados 49100 archivos
Procesados 49200 archivos
Procesados 49300 archivos
Procesados 49400 archivos
Procesados 49500 archivos
Procesados 49600 archivos
Procesados 49700 archivos
Procesados 49800 archivos
Procesados 49900 archivos

In [ ]:
output_path = os.path.join(dataset_directory, "train_source.parquet")

In [ ]:
%cd {dataset_directory}

/content/drive/.shortcut-targets-by-id/1Xut7nWIe-55SLuAofdhgyG3ekr1fIvsa/IA y Compiladores/Reto_plagio/dataset

In [ ]:
%ls {output_path}

'/content/drive/MyDrive/IA y Compiladores/Reto_plagio/dataset/train_source.parquet'

In [ ]:
"""
train_source.to_parquet(
    "train_source.parquet",
    index=False
)

print(f"Guardado en: {output_path}")
"""

Guardado en: /content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio/dataset/train_source.parquet

In [ ]:
train_source = pd.read_parquet("train_source.parquet")

In [ ]:
train_source

,uid,pid,source_code,num_chars,num_lines
0,415,27909,/*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...,4144,158
1,415,55938,/*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...,2840,90
2,415,90936,/*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...,2762,94
3,415,56858,/*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...,3094,105
4,415,9447,/*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...,2603,83
...,...,...,...,...,...
49995,276,62598,#include <iostream>\n#include<bits/stdc++.h>\n...,1950,103
49996,276,56580,#define _CRT_SECURE_NO_WARNINGS 1\n#include <i...,1834,93
49997,276,52656,#define _CRT_SECURE_NO_WARNINGS 1\n#include <v...,2235,100
49998,276,3563,#define _CRT_SECURE_NO_WARNINGS 1\n#include <v...,2225,95
49999,276,75845,#define _CRT_SECURE_NO_WARNINGS 1\n#include <v...,3132,134

Hacer la lectura de forma paralela

In [ ]:
def process_chunk(path, chunk_df, worker_id):

    records = []

    total = len(chunk_df)

    for idx, row in enumerate(chunk_df.itertuples(index=False), start=1):

        pid = str(row.pid)

        file_path = os.path.join(path, pid)

        try:
            with open(file_path, "r", encoding="utf-8") as f:

                source_code = f.read()

            records.append({
                "uid": row.uid,
                "pid": pid,
                "source_code": source_code,
                "num_chars": len(source_code),
                "num_lines": source_code.count("\n") + 1
            })

        except Exception as e:
            print(f"Error en {pid}: {e}")

        if idx % 100 == 0:
            print(
                f"[Worker {worker_id}] "
                f"{idx}/{total} archivos procesados"
            )

    return pd.DataFrame(records)


def build_source_dataframe_parallel(path, metadata_df, workers=5):

    chunks = np.array_split(metadata_df, workers)

    with ThreadPoolExecutor(max_workers=workers) as executor:

        futures = [
            executor.submit(process_chunk, path, chunk, worker_id)
            for worker_id, chunk in enumerate(chunks, start=1)
        ]

        dfs = [future.result() for future in futures]

    return pd.concat(dfs, ignore_index=True)

In [ ]:
%cd {dataset_directory}

/content/drive/.shortcut-targets-by-id/1Xut7nWIe-55SLuAofdhgyG3ekr1fIvsa/IA y Compiladores/Reto_plagio/dataset

In [ ]:
!ls

checkpoint_m1  dev	test		     train	train_source.parquet
dataset        dev.csv	tokens_official.csv  train.csv	unlabeled_test.csv

## Dev/Validation

In [ ]:
dev_source = build_source_dataframe_parallel(
    path="./dev",
    metadata_df=df_validation,
    workers=5
)

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

[Worker 1] 100/5000 archivos procesados
[Worker 2] 100/5000 archivos procesados
[Worker 3] 100/5000 archivos procesados
[Worker 5] 100/5000 archivos procesados
[Worker 4] 100/5000 archivos procesados
[Worker 1] 200/5000 archivos procesados
[Worker 2] 200/5000 archivos procesados
[Worker 3] 200/5000 archivos procesados
[Worker 5] 200/5000 archivos procesados
[Worker 4] 200/5000 archivos procesados
[Worker 1] 300/5000 archivos procesados
[Worker 2] 300/5000 archivos procesados
[Worker 3] 300/5000 archivos procesados
[Worker 4] 300/5000 archivos procesados
[Worker 5] 300/5000 archivos procesados
[Worker 5] 400/5000 archivos procesados
[Worker 1] 400/5000 archivos procesados
[Worker 3] 400/5000 archivos procesados
[Worker 2] 400/5000 archivos procesados
[Worker 4] 400/5000 archivos procesados
[Worker 1] 500/5000 archivos procesados
[Worker 3] 500/5000 archivos procesados
[Worker 4] 500/5000 archivos procesados
[Worker 2] 500/5000 archivos procesados
[Worker 5] 500/5000 archivos procesados
[Worker 1] 600/5000 archivos procesados
[Worker 3] 600/5000 archivos procesados
[Worker 4] 600/5000 archivos procesados
[Worker 2] 600/5000 archivos procesados
[Worker 5] 600/5000 archivos procesados
[Worker 1] 700/5000 archivos procesados
[Worker 3] 700/5000 archivos procesados
[Worker 5] 700/5000 archivos procesados
[Worker 4] 700/5000 archivos procesados
[Worker 2] 700/5000 archivos procesados
[Worker 1] 800/5000 archivos procesados
[Worker 3] 800/5000 archivos procesados
[Worker 5] 800/5000 archivos procesados
[Worker 4] 800/5000 archivos procesados
[Worker 2] 800/5000 archivos procesados
[Worker 1] 900/5000 archivos procesados
[Worker 3] 900/5000 archivos procesados
[Worker 4] 900/5000 archivos procesados
[Worker 5] 900/5000 archivos procesados
[Worker 2] 900/5000 archivos procesados
[Worker 1] 1000/5000 archivos procesados
[Worker 3] 1000/5000 archivos procesados
[Worker 4] 1000/5000 archivos procesados
[Worker 5] 1000/5000 archivos procesados
[Worker 2] 1000/5000 archivos procesados
[Worker 1] 1100/5000 archivos procesados
[Worker 3] 1100/5000 archivos procesados
[Worker 4] 1100/5000 archivos procesados
[Worker 5] 1100/5000 archivos procesados
[Worker 2] 1100/5000 archivos procesados
[Worker 1] 1200/5000 archivos procesados
[Worker 3] 1200/5000 archivos procesados
[Worker 5] 1200/5000 archivos procesados
[Worker 4] 1200/5000 archivos procesados
[Worker 2] 1200/5000 archivos procesados
[Worker 1] 1300/5000 archivos procesados
[Worker 3] 1300/5000 archivos procesados
[Worker 4] 1300/5000 archivos procesados
[Worker 5] 1300/5000 archivos procesados
[Worker 2] 1300/5000 archivos procesados
[Worker 1] 1400/5000 archivos procesados
[Worker 3] 1400/5000 archivos procesados
[Worker 4] 1400/5000 archivos procesados
[Worker 5] 1400/5000 archivos procesados
[Worker 2] 1400/5000 archivos procesados
[Worker 1] 1500/5000 archivos procesados
[Worker 3] 1500/5000 archivos procesados
[Worker 4] 1500/5000 archivos procesados
[Worker 5] 1500/5000 archivos procesados
[Worker 2] 1500/5000 archivos procesados
[Worker 1] 1600/5000 archivos procesados
[Worker 3] 1600/5000 archivos procesados
[Worker 4] 1600/5000 archivos procesados
[Worker 5] 1600/5000 archivos procesados
[Worker 2] 1600/5000 archivos procesados
[Worker 1] 1700/5000 archivos procesados
[Worker 3] 1700/5000 archivos procesados
[Worker 4] 1700/5000 archivos procesados
[Worker 5] 1700/5000 archivos procesados
[Worker 2] 1700/5000 archivos procesados
[Worker 1] 1800/5000 archivos procesados
[Worker 4] 1800/5000 archivos procesados
[Worker 3] 1800/5000 archivos procesados
[Worker 5] 1800/5000 archivos procesados
[Worker 2] 1800/5000 archivos procesados
[Worker 1] 1900/5000 archivos procesados
[Worker 4] 1900/5000 archivos procesados
[Worker 3] 1900/5000 archivos procesados
[Worker 5] 1900/5000 archivos procesados
[Worker 2] 1900/5000 archivos procesados
[Worker 1] 2000/5000 archivos procesados
[Worker 4] 2000/5000 archivos procesados
[Worker 3] 2000/5000 archivos procesados
[Worker 5] 2000/5000 archivos procesados
[Worker 2] 2000/5000 archivos procesados
[Worker 1] 2100/5000 archivos procesados
[Worker 4] 2100/5000 archivos procesados
[Worker 3] 2100/5000 archivos procesados
[Worker 5] 2100/5000 archivos procesados
[Worker 2] 2100/5000 archivos procesados
[Worker 1] 2200/5000 archivos procesados
[Worker 4] 2200/5000 archivos procesados
[Worker 3] 2200/5000 archivos procesados
[Worker 5] 2200/5000 archivos procesados
[Worker 2] 2200/5000 archivos procesados
[Worker 1] 2300/5000 archivos procesados
[Worker 4] 2300/5000 archivos procesados
[Worker 5] 2300/5000 archivos procesados
[Worker 3] 2300/5000 archivos procesados
[Worker 2] 2300/5000 archivos procesados
[Worker 1] 2400/5000 archivos procesados
[Worker 4] 2400/5000 archivos procesados
[Worker 5] 2400/5000 archivos procesados
[Worker 3] 2400/5000 archivos procesados
[Worker 2] 2400/5000 archivos procesados
[Worker 1] 2500/5000 archivos procesados
[Worker 4] 2500/5000 archivos procesados
[Worker 3] 2500/5000 archivos procesados
[Worker 5] 2500/5000 archivos procesados
[Worker 2] 2500/5000 archivos procesados
[Worker 1] 2600/5000 archivos procesados
[Worker 4] 2600/5000 archivos procesados
[Worker 3] 2600/5000 archivos procesados
[Worker 5] 2600/5000 archivos procesados
[Worker 2] 2600/5000 archivos procesados
[Worker 1] 2700/5000 archivos procesados
[Worker 3] 2700/5000 archivos procesados
[Worker 4] 2700/5000 archivos procesados
[Worker 5] 2700/5000 archivos procesados
[Worker 2] 2700/5000 archivos procesados
[Worker 1] 2800/5000 archivos procesados
[Worker 5] 2800/5000 archivos procesados
[Worker 4] 2800/5000 archivos procesados
[Worker 3] 2800/5000 archivos procesados
[Worker 2] 2800/5000 archivos procesados
[Worker 1] 2900/5000 archivos procesados
[Worker 5] 2900/5000 archivos procesados
[Worker 3] 2900/5000 archivos procesados
[Worker 4] 2900/5000 archivos procesados
[Worker 2] 2900/5000 archivos procesados
[Worker 1] 3000/5000 archivos procesados
[Worker 4] 3000/5000 archivos procesados
[Worker 5] 3000/5000 archivos procesados
[Worker 3] 3000/5000 archivos procesados
[Worker 2] 3000/5000 archivos procesados
[Worker 1] 3100/5000 archivos procesados
[Worker 4] 3100/5000 archivos procesados
[Worker 5] 3100/5000 archivos procesados
[Worker 3] 3100/5000 archivos procesados
[Worker 2] 3100/5000 archivos procesados
[Worker 1] 3200/5000 archivos procesados
[Worker 4] 3200/5000 archivos procesados
[Worker 5] 3200/5000 archivos procesados
[Worker 3] 3200/5000 archivos procesados
[Worker 2] 3200/5000 archivos procesados
[Worker 1] 3300/5000 archivos procesados
[Worker 4] 3300/5000 archivos procesados
[Worker 2] 3300/5000 archivos procesados
[Worker 3] 3300/5000 archivos procesados
[Worker 5] 3300/5000 archivos procesados
[Worker 1] 3400/5000 archivos procesados
[Worker 4] 3400/5000 archivos procesados
[Worker 2] 3400/5000 archivos procesados
[Worker 3] 3400/5000 archivos procesados
[Worker 5] 3400/5000 archivos procesados
[Worker 1] 3500/5000 archivos procesados
[Worker 4] 3500/5000 archivos procesados
[Worker 2] 3500/5000 archivos procesados
[Worker 5] 3500/5000 archivos procesados
[Worker 3] 3500/5000 archivos procesados
[Worker 1] 3600/5000 archivos procesados
[Worker 4] 3600/5000 archivos procesados
[Worker 2] 3600/5000 archivos procesados
[Worker 5] 3600/5000 archivos procesados
[Worker 3] 3600/5000 archivos procesados
[Worker 1] 3700/5000 archivos procesados
[Worker 4] 3700/5000 archivos procesados
[Worker 2] 3700/5000 archivos procesados
[Worker 5] 3700/5000 archivos procesados
[Worker 3] 3700/5000 archivos procesados
[Worker 1] 3800/5000 archivos procesados
[Worker 4] 3800/5000 archivos procesados
[Worker 2] 3800/5000 archivos procesados
[Worker 5] 3800/5000 archivos procesados
[Worker 3] 3800/5000 archivos procesados
[Worker 1] 3900/5000 archivos procesados
[Worker 4] 3900/5000 archivos procesados
[Worker 2] 3900/5000 archivos procesados
[Worker 5] 3900/5000 archivos procesados
[Worker 3] 3900/5000 archivos procesados
[Worker 1] 4000/5000 archivos procesados
[Worker 4] 4000/5000 archivos procesados
[Worker 2] 4000/5000 archivos procesados
[Worker 5] 4000/5000 archivos procesados
[Worker 3] 4000/5000 archivos procesados
[Worker 1] 4100/5000 archivos procesados
[Worker 2] 4100/5000 archivos procesados
[Worker 4] 4100/5000 archivos procesados
[Worker 5] 4100/5000 archivos procesados
[Worker 3] 4100/5000 archivos procesados
[Worker 1] 4200/5000 archivos procesados
[Worker 2] 4200/5000 archivos procesados
[Worker 4] 4200/5000 archivos procesados
[Worker 5] 4200/5000 archivos procesados
[Worker 3] 4200/5000 archivos procesados
[Worker 1] 4300/5000 archivos procesados
[Worker 2] 4300/5000 archivos procesados
[Worker 4] 4300/5000 archivos procesados
[Worker 3] 4300/5000 archivos procesados
[Worker 5] 4300/5000 archivos procesados
[Worker 1] 4400/5000 archivos procesados
[Worker 2] 4400/5000 archivos procesados
[Worker 4] 4400/5000 archivos procesados
[Worker 5] 4400/5000 archivos procesados
[Worker 3] 4400/5000 archivos procesados
[Worker 1] 4500/5000 archivos procesados
[Worker 2] 4500/5000 archivos procesados
[Worker 4] 4500/5000 archivos procesados
[Worker 5] 4500/5000 archivos procesados
[Worker 3] 4500/5000 archivos procesados
[Worker 1] 4600/5000 archivos procesados
[Worker 2] 4600/5000 archivos procesados
[Worker 4] 4600/5000 archivos procesados
[Worker 5] 4600/5000 archivos procesados
[Worker 3] 4600/5000 archivos procesados
[Worker 1] 4700/5000 archivos procesados
[Worker 2] 4700/5000 archivos procesados
[Worker 4] 4700/5000 archivos procesados
[Worker 5] 4700/5000 archivos procesados
[Worker 3] 4700/5000 archivos procesados
[Worker 1] 4800/5000 archivos procesados
[Worker 2] 4800/5000 archivos procesados
[Worker 4] 4800/5000 archivos procesados
[Worker 3] 4800/5000 archivos procesados
[Worker 5] 4800/5000 archivos procesados
[Worker 1] 4900/5000 archivos procesados
[Worker 2] 4900/5000 archivos procesados
[Worker 4] 4900/5000 archivos procesados
[Worker 5] 4900/5000 archivos procesados
[Worker 3] 4900/5000 archivos procesados
[Worker 1] 5000/5000 archivos procesados
[Worker 2] 5000/5000 archivos procesados
[Worker 4] 5000/5000 archivos procesados
[Worker 5] 5000/5000 archivos procesados
[Worker 3] 5000/5000 archivos procesados

In [ ]:
dev_source

,uid,pid,source_code,num_chars,num_lines
0,415,12180,/*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...,2656,80
1,415,67901,/*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...,2629,83
2,415,76245,/*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...,3280,111
3,415,70953,/*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...,2586,83
4,415,41256,/*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...,3395,117
...,...,...,...,...,...
24995,276,57950,#define _CRT_SECURE_NO_WARNINGS 1\n#include <v...,1664,77
24996,276,53982,#include<iostream>\n#include<algorithm>\n#incl...,685,32
24997,276,88752,#define _CRT_SECURE_NO_WARNINGS 1\n#include <v...,2664,104
24998,276,81705,#define _CRT_SECURE_NO_WARNINGS 1\n#include <v...,1344,54
24999,276,88570,#include<iostream>\n#include<string>\n#include...,470,28

In [ ]:
%cd {dataset_directory}

/content/drive/.shortcut-targets-by-id/1Xut7nWIe-55SLuAofdhgyG3ekr1fIvsa/IA y Compiladores/Reto_plagio/dataset

In [ ]:
dev_source.to_parquet(
    "dev_source.parquet",
    index=False
)

print(f"Guardado en: {output_path}")

Guardado en: /content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio/dataset/train_source.parquet

## Test

In [ ]:
%cd {dataset_directory}

/content/drive/.shortcut-targets-by-id/1Xut7nWIe-55SLuAofdhgyG3ekr1fIvsa/IA y Compiladores/Reto_plagio/dataset

In [ ]:
!ls

checkpoint_m1  dev.csv		   tokens_official.csv	train_source.parquet
dataset        dev_source.parquet  train		unlabeled_test.csv
dev	       test		   train.csv

In [ ]:
test_source = build_source_dataframe_parallel(
    path="./test",
    metadata_df=df_test,
    workers=10
)

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

[Worker 2] 100/2500 archivos procesados
[Worker 1] 100/2500 archivos procesados
[Worker 3] 100/2500 archivos procesados
[Worker 4] 100/2500 archivos procesados
[Worker 5] 100/2500 archivos procesados
[Worker 9] 100/2500 archivos procesados
[Worker 6] 100/2500 archivos procesados
[Worker 7] 100/2500 archivos procesados
[Worker 8] 100/2500 archivos procesados
[Worker 10] 100/2500 archivos procesados
[Worker 2] 200/2500 archivos procesados
[Worker 3] 200/2500 archivos procesados
[Worker 4] 200/2500 archivos procesados
[Worker 5] 200/2500 archivos procesados
[Worker 9] 200/2500 archivos procesados
[Worker 1] 200/2500 archivos procesados
[Worker 6] 200/2500 archivos procesados
[Worker 10] 200/2500 archivos procesados
[Worker 8] 200/2500 archivos procesados
[Worker 7] 200/2500 archivos procesados
[Worker 3] 4800/5000 archivos procesados
[Worker 4] 4800/5000 archivos procesados
[Worker 2] 300/2500 archivos procesados
[Worker 4] 300/2500 archivos procesados
[Worker 3] 300/2500 archivos procesados
[Worker 5] 300/2500 archivos procesados
[Worker 1] 300/2500 archivos procesados
[Worker 9] 300/2500 archivos procesados
[Worker 7] 300/2500 archivos procesados
[Worker 6] 300/2500 archivos procesados
[Worker 10] 300/2500 archivos procesados
[Worker 8] 300/2500 archivos procesados
[Worker 2] 400/2500 archivos procesados
[Worker 4] 400/2500 archivos procesados
[Worker 3] 400/2500 archivos procesados
[Worker 5] 400/2500 archivos procesados
[Worker 1] 400/2500 archivos procesados
[Worker 9] 400/2500 archivos procesados
[Worker 7] 400/2500 archivos procesados
[Worker 6] 400/2500 archivos procesados
[Worker 10] 400/2500 archivos procesados
[Worker 8] 400/2500 archivos procesados
[Worker 2] 500/2500 archivos procesados
[Worker 4] 500/2500 archivos procesados
[Worker 3] 500/2500 archivos procesados
[Worker 5] 500/2500 archivos procesados
[Worker 9] 500/2500 archivos procesados
[Worker 1] 500/2500 archivos procesados
[Worker 7] 500/2500 archivos procesados
[Worker 6] 500/2500 archivos procesados
[Worker 10] 500/2500 archivos procesados
[Worker 8] 500/2500 archivos procesados
[Worker 2] 600/2500 archivos procesados
[Worker 4] 600/2500 archivos procesados
[Worker 5] 600/2500 archivos procesados
[Worker 3] 600/2500 archivos procesados
[Worker 9] 600/2500 archivos procesados
[Worker 1] 600/2500 archivos procesados
[Worker 7] 600/2500 archivos procesados
[Worker 6] 600/2500 archivos procesados
[Worker 10] 600/2500 archivos procesados
[Worker 8] 600/2500 archivos procesados
[Worker 2] 700/2500 archivos procesados
[Worker 5] 700/2500 archivos procesados
[Worker 4] 700/2500 archivos procesados
[Worker 3] 700/2500 archivos procesados
[Worker 1] 700/2500 archivos procesados
[Worker 7] 700/2500 archivos procesados
[Worker 6] 700/2500 archivos procesados
[Worker 9] 700/2500 archivos procesados
[Worker 10] 700/2500 archivos procesados
[Worker 8] 700/2500 archivos procesados
[Worker 2] 800/2500 archivos procesados
[Worker 5] 800/2500 archivos procesados
[Worker 4] 800/2500 archivos procesados
[Worker 3] 800/2500 archivos procesados
[Worker 1] 800/2500 archivos procesados
[Worker 9] 800/2500 archivos procesados
[Worker 7] 800/2500 archivos procesados
[Worker 6] 800/2500 archivos procesados
[Worker 10] 800/2500 archivos procesados
[Worker 8] 800/2500 archivos procesados
[Worker 2] 900/2500 archivos procesados
[Worker 5] 900/2500 archivos procesados
[Worker 4] 900/2500 archivos procesados
[Worker 3] 900/2500 archivos procesados
[Worker 1] 900/2500 archivos procesados
[Worker 7] 900/2500 archivos procesados
[Worker 9] 900/2500 archivos procesados
[Worker 6] 900/2500 archivos procesados
[Worker 10] 900/2500 archivos procesados
[Worker 8] 900/2500 archivos procesados
[Worker 2] 1000/2500 archivos procesados
[Worker 5] 1000/2500 archivos procesados
[Worker 4] 1000/2500 archivos procesados
[Worker 3] 1000/2500 archivos procesados
[Worker 1] 1000/2500 archivos procesados
[Worker 7] 1000/2500 archivos procesados
[Worker 9] 1000/2500 archivos procesados
[Worker 6] 1000/2500 archivos procesados
[Worker 10] 1000/2500 archivos procesados
[Worker 8] 1000/2500 archivos procesados
[Worker 2] 1100/2500 archivos procesados
[Worker 5] 1100/2500 archivos procesados
[Worker 4] 1100/2500 archivos procesados
[Worker 3] 1100/2500 archivos procesados
[Worker 7] 1100/2500 archivos procesados
[Worker 1] 1100/2500 archivos procesados
[Worker 9] 1100/2500 archivos procesados
[Worker 6] 1100/2500 archivos procesados
[Worker 10] 1100/2500 archivos procesados
[Worker 8] 1100/2500 archivos procesados
[Worker 2] 1200/2500 archivos procesados
[Worker 5] 1200/2500 archivos procesados
[Worker 4] 1200/2500 archivos procesados
[Worker 3] 1200/2500 archivos procesados
[Worker 7] 1200/2500 archivos procesados
[Worker 1] 1200/2500 archivos procesados
[Worker 9] 1200/2500 archivos procesados
[Worker 6] 1200/2500 archivos procesados
[Worker 10] 1200/2500 archivos procesados
[Worker 8] 1200/2500 archivos procesados
[Worker 1] 4900/5000 archivos procesados
[Worker 2] 1300/2500 archivos procesados
[Worker 4] 1300/2500 archivos procesados
[Worker 5] 1300/2500 archivos procesados
[Worker 3] 1300/2500 archivos procesados
[Worker 1] 1300/2500 archivos procesados
[Worker 7] 1300/2500 archivos procesados
[Worker 6] 1300/2500 archivos procesados
[Worker 9] 1300/2500 archivos procesados
[Worker 8] 1300/2500 archivos procesados
[Worker 10] 1300/2500 archivos procesados
[Worker 4] 1400/2500 archivos procesados
[Worker 2] 1400/2500 archivos procesados
[Worker 1] 1400/2500 archivos procesados
[Worker 5] 1400/2500 archivos procesados
[Worker 3] 1400/2500 archivos procesados
[Worker 7] 1400/2500 archivos procesados
[Worker 9] 1400/2500 archivos procesados
[Worker 6] 1400/2500 archivos procesados
[Worker 8] 1400/2500 archivos procesados
[Worker 10] 1400/2500 archivos procesados
[Worker 2] 1500/2500 archivos procesados
[Worker 4] 1500/2500 archivos procesados
[Worker 5] 1500/2500 archivos procesados
[Worker 3] 1500/2500 archivos procesados
[Worker 1] 1500/2500 archivos procesados
[Worker 6] 1500/2500 archivos procesados
[Worker 7] 1500/2500 archivos procesados
[Worker 9] 1500/2500 archivos procesados
[Worker 8] 1500/2500 archivos procesados
[Worker 10] 1500/2500 archivos procesados
[Worker 5] 4900/5000 archivos procesados
[Worker 2] 1600/2500 archivos procesados
[Worker 4] 1600/2500 archivos procesados
[Worker 5] 1600/2500 archivos procesados
[Worker 3] 1600/2500 archivos procesados
[Worker 1] 1600/2500 archivos procesados
[Worker 6] 1600/2500 archivos procesados
[Worker 7] 1600/2500 archivos procesados
[Worker 9] 1600/2500 archivos procesados
[Worker 8] 1600/2500 archivos procesados
[Worker 10] 1600/2500 archivos procesados
[Worker 2] 4900/5000 archivos procesados
[Worker 2] 1700/2500 archivos procesados
[Worker 4] 1700/2500 archivos procesados
[Worker 5] 1700/2500 archivos procesados
[Worker 1] 1700/2500 archivos procesados
[Worker 3] 1700/2500 archivos procesados
[Worker 6] 1700/2500 archivos procesados
[Worker 7] 1700/2500 archivos procesados
[Worker 8] 1700/2500 archivos procesados
[Worker 9] 1700/2500 archivos procesados
[Worker 10] 1700/2500 archivos procesados
[Worker 2] 1800/2500 archivos procesados
[Worker 4] 1800/2500 archivos procesados
[Worker 5] 1800/2500 archivos procesados
[Worker 1] 1800/2500 archivos procesados
[Worker 3] 1800/2500 archivos procesados
[Worker 6] 1800/2500 archivos procesados
[Worker 7] 1800/2500 archivos procesados
[Worker 8] 1800/2500 archivos procesados
[Worker 9] 1800/2500 archivos procesados
[Worker 10] 1800/2500 archivos procesados
[Worker 3] 4900/5000 archivos procesados
[Worker 4] 4900/5000 archivos procesados
[Worker 2] 1900/2500 archivos procesados
[Worker 4] 1900/2500 archivos procesados
[Worker 5] 1900/2500 archivos procesados
[Worker 1] 1900/2500 archivos procesados
[Worker 3] 1900/2500 archivos procesados
[Worker 6] 1900/2500 archivos procesados
[Worker 7] 1900/2500 archivos procesados
[Worker 8] 1900/2500 archivos procesados
[Worker 9] 1900/2500 archivos procesados
[Worker 10] 1900/2500 archivos procesados
[Worker 2] 2000/2500 archivos procesados
[Worker 5] 2000/2500 archivos procesados
[Worker 4] 2000/2500 archivos procesados
[Worker 3] 2000/2500 archivos procesados
[Worker 1] 2000/2500 archivos procesados
[Worker 6] 2000/2500 archivos procesados
[Worker 8] 2000/2500 archivos procesados
[Worker 7] 2000/2500 archivos procesados
[Worker 9] 2000/2500 archivos procesados
[Worker 10] 2000/2500 archivos procesados
[Worker 2] 2100/2500 archivos procesados
[Worker 4] 2100/2500 archivos procesados
[Worker 8] 2100/2500 archivos procesados
[Worker 5] 2100/2500 archivos procesados
[Worker 3] 2100/2500 archivos procesados
[Worker 7] 2100/2500 archivos procesados
[Worker 6] 2100/2500 archivos procesados
[Worker 1] 2100/2500 archivos procesados
[Worker 9] 2100/2500 archivos procesados
[Worker 10] 2100/2500 archivos procesados
[Worker 2] 2200/2500 archivos procesados
[Worker 4] 2200/2500 archivos procesados
[Worker 8] 2200/2500 archivos procesados
[Worker 5] 2200/2500 archivos procesados
[Worker 3] 2200/2500 archivos procesados
[Worker 6] 2200/2500 archivos procesados
[Worker 7] 2200/2500 archivos procesados
[Worker 1] 2200/2500 archivos procesados
[Worker 9] 2200/2500 archivos procesados
[Worker 10] 2200/2500 archivos procesados
[Worker 2] 2300/2500 archivos procesados
[Worker 8] 2300/2500 archivos procesados
[Worker 4] 2300/2500 archivos procesados
[Worker 5] 2300/2500 archivos procesados
[Worker 3] 2300/2500 archivos procesados
[Worker 6] 2300/2500 archivos procesados
[Worker 7] 2300/2500 archivos procesados
[Worker 1] 2300/2500 archivos procesados
[Worker 9] 2300/2500 archivos procesados
[Worker 10] 2300/2500 archivos procesados
[Worker 2] 2400/2500 archivos procesados
[Worker 4] 2400/2500 archivos procesados
[Worker 8] 2400/2500 archivos procesados
[Worker 3] 2400/2500 archivos procesados
[Worker 5] 2400/2500 archivos procesados
[Worker 6] 2400/2500 archivos procesados
[Worker 1] 2400/2500 archivos procesados
[Worker 7] 2400/2500 archivos procesados
[Worker 9] 2400/2500 archivos procesados
[Worker 10] 2400/2500 archivos procesados
[Worker 3] 2500/2500 archivos procesados
[Worker 5] 2500/2500 archivos procesados
[Worker 7] 2500/2500 archivos procesados
[Worker 1] 2500/2500 archivos procesados
[Worker 9] 2500/2500 archivos procesados
[Worker 2] 2500/2500 archivos procesados
[Worker 1] 5000/5000 archivos procesados
[Worker 10] 2500/2500 archivos procesados[Worker 5] 5000/5000 archivos procesados

[Worker 4] 2500/2500 archivos procesados
[Worker 2] 5000/5000 archivos procesados
[Worker 6] 2500/2500 archivos procesados[Worker 3] 5000/5000 archivos procesados

[Worker 8] 2500/2500 archivos procesados
[Worker 4] 5000/5000 archivos procesados

In [ ]:
test_source

,uid,pid,source_code,num_chars,num_lines
0,NaN,34841,"///If I see that thing, I'ma squash it\n///and...",634,33
1,NaN,68320,/*input\n1\n1\n\n*/\n \n/*\n ...,3100,125
2,NaN,72734,#include <algorithm>\n#include <iostream>\n#in...,1576,81
3,NaN,55803,//HASHEMESHOON hastam ;)\n#include <iostream>\...,682,31
4,NaN,96166,#include <functional>\n#include <algorithm>\n#...,3410,166
...,...,...,...,...,...
24995,NaN,54090,#include <iostream>\nusing namespace std;\n\nl...,194,14
24996,NaN,62563,#include <bits/stdc++.h>\nusing namespace std;...,230,16
24997,NaN,45920,#include <bits/stdc++.h>\n#define pb push_back...,2021,80
24998,NaN,81447,#include <bits/stdc++.h>\n#define int __int64\...,550,27
24999,NaN,94031,"/////////////////////////////\n//Just Smile, M...",1159,63

In [ ]:
test_source.to_parquet(
    "test_source.parquet",
    index=False
)

print(f"Guardado en: {output_path}")

Guardado en: /content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio/dataset/train_source.parquet

# Obtener tokens

In [ ]:
tokenizer_bert = BertTokenizer.from_pretrained(
    'bert-base-uncased'
)

def split_tokens(text, chunk_size=400):
    tokens = tokenizer_bert.tokenize(text)
    return [
        tokens[i:i + chunk_size]
        for i in range(0, len(tokens), chunk_size)
    ]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
def tokenize_source_code(text):

  if not isinstance(text, str) or len(text.strip()) == 0:
        return pd.DataFrame()

  encoded = tokenizer_bert(
      text,
      max_length=512,
      truncation=True,
      return_overflowing_tokens=True,
      padding=False
  )

  rows = []

  for chunk_id, token_ids in enumerate(encoded["input_ids"]):

    rows.append({
        "chunk_id": chunk_id,
        "token_ids": token_ids,
        "num_tokens": len(token_ids)
    })

  return pd.DataFrame(rows)

def build_tokens_dataframe(source_df):
  all_chunks = []

  total = len(source_df)

  for idx, row in enumerate(source_df.itertuples(index=False),start=1):

      chunks_df = tokenize_source_code(row.source_code)

      if chunks_df.empty:
        continue

      chunks_df["uid"] = row.uid
      chunks_df["pid"] = row.pid

      all_chunks.append(chunks_df)

      if idx % 100 == 0:
          print(f"{idx}/{total} archivos tokenizados")

  return pd.concat(all_chunks, ignore_index=True)

In [ ]:
train_tokens = build_tokens_dataframe(train_source)

100/50000 archivos tokenizados
200/50000 archivos tokenizados
300/50000 archivos tokenizados
400/50000 archivos tokenizados
500/50000 archivos tokenizados
600/50000 archivos tokenizados
700/50000 archivos tokenizados
800/50000 archivos tokenizados
900/50000 archivos tokenizados
1000/50000 archivos tokenizados
1100/50000 archivos tokenizados
1200/50000 archivos tokenizados
1300/50000 archivos tokenizados
1400/50000 archivos tokenizados
1500/50000 archivos tokenizados
1600/50000 archivos tokenizados
1700/50000 archivos tokenizados
1800/50000 archivos tokenizados
1900/50000 archivos tokenizados
2000/50000 archivos tokenizados
2100/50000 archivos tokenizados
2200/50000 archivos tokenizados
2300/50000 archivos tokenizados
2400/50000 archivos tokenizados
2500/50000 archivos tokenizados
2600/50000 archivos tokenizados
2700/50000 archivos tokenizados
2800/50000 archivos tokenizados
2900/50000 archivos tokenizados
3000/50000 archivos tokenizados
3100/50000 archivos tokenizados
3200/50000 archivos tokenizados
3300/50000 archivos tokenizados
3400/50000 archivos tokenizados
3500/50000 archivos tokenizados
3600/50000 archivos tokenizados
3700/50000 archivos tokenizados
3800/50000 archivos tokenizados
3900/50000 archivos tokenizados
4000/50000 archivos tokenizados
4100/50000 archivos tokenizados
4200/50000 archivos tokenizados
4300/50000 archivos tokenizados
4400/50000 archivos tokenizados
4500/50000 archivos tokenizados
4600/50000 archivos tokenizados
4700/50000 archivos tokenizados
4800/50000 archivos tokenizados
4900/50000 archivos tokenizados
5000/50000 archivos tokenizados
5100/50000 archivos tokenizados
5200/50000 archivos tokenizados
5300/50000 archivos tokenizados
5400/50000 archivos tokenizados
5500/50000 archivos tokenizados
5600/50000 archivos tokenizados
5700/50000 archivos tokenizados
5800/50000 archivos tokenizados
5900/50000 archivos tokenizados
6000/50000 archivos tokenizados
6100/50000 archivos tokenizados
6200/50000 archivos tokenizados
6300/50000 archivos tokenizados
6400/50000 archivos tokenizados
6500/50000 archivos tokenizados
6600/50000 archivos tokenizados
6700/50000 archivos tokenizados
6800/50000 archivos tokenizados
6900/50000 archivos tokenizados
7000/50000 archivos tokenizados
7100/50000 archivos tokenizados
7200/50000 archivos tokenizados
7300/50000 archivos tokenizados
7400/50000 archivos tokenizados
7500/50000 archivos tokenizados
7600/50000 archivos tokenizados
7700/50000 archivos tokenizados
7800/50000 archivos tokenizados
7900/50000 archivos tokenizados
8000/50000 archivos tokenizados
8100/50000 archivos tokenizados
8200/50000 archivos tokenizados
8300/50000 archivos tokenizados
8400/50000 archivos tokenizados
8500/50000 archivos tokenizados
8600/50000 archivos tokenizados
8700/50000 archivos tokenizados
8800/50000 archivos tokenizados
8900/50000 archivos tokenizados
9000/50000 archivos tokenizados
9100/50000 archivos tokenizados
9200/50000 archivos tokenizados
9300/50000 archivos tokenizados
9400/50000 archivos tokenizados
9500/50000 archivos tokenizados
9600/50000 archivos tokenizados
9700/50000 archivos tokenizados
9800/50000 archivos tokenizados
9900/50000 archivos tokenizados
10000/50000 archivos tokenizados
10100/50000 archivos tokenizados
10200/50000 archivos tokenizados
10300/50000 archivos tokenizados
10400/50000 archivos tokenizados
10500/50000 archivos tokenizados
10600/50000 archivos tokenizados
10700/50000 archivos tokenizados
10800/50000 archivos tokenizados
10900/50000 archivos tokenizados
11000/50000 archivos tokenizados
11100/50000 archivos tokenizados
11200/50000 archivos tokenizados
11300/50000 archivos tokenizados
11400/50000 archivos tokenizados
11500/50000 archivos tokenizados
11600/50000 archivos tokenizados
11700/50000 archivos tokenizados
11800/50000 archivos tokenizados
11900/50000 archivos tokenizados
12000/50000 archivos tokenizados
12100/50000 archivos tokenizados
12200/50000 archivos tokenizados
12300/50000 archivos tokenizados
12400/50000 archivos tokenizados
12500/50000 archivos tokenizados
12600/50000 archivos tokenizados
12700/50000 archivos tokenizados
12800/50000 archivos tokenizados
12900/50000 archivos tokenizados
13000/50000 archivos tokenizados
13100/50000 archivos tokenizados
13200/50000 archivos tokenizados
13300/50000 archivos tokenizados
13400/50000 archivos tokenizados
13500/50000 archivos tokenizados
13600/50000 archivos tokenizados
13700/50000 archivos tokenizados
13800/50000 archivos tokenizados
13900/50000 archivos tokenizados
14000/50000 archivos tokenizados
14100/50000 archivos tokenizados
14200/50000 archivos tokenizados
14300/50000 archivos tokenizados
14400/50000 archivos tokenizados
14500/50000 archivos tokenizados
14600/50000 archivos tokenizados
14700/50000 archivos tokenizados
14800/50000 archivos tokenizados
14900/50000 archivos tokenizados
15000/50000 archivos tokenizados
15100/50000 archivos tokenizados
15200/50000 archivos tokenizados
15300/50000 archivos tokenizados
15400/50000 archivos tokenizados
15500/50000 archivos tokenizados
15600/50000 archivos tokenizados
15700/50000 archivos tokenizados
15800/50000 archivos tokenizados
15900/50000 archivos tokenizados
16000/50000 archivos tokenizados
16100/50000 archivos tokenizados
16200/50000 archivos tokenizados
16300/50000 archivos tokenizados
16400/50000 archivos tokenizados
16500/50000 archivos tokenizados
16600/50000 archivos tokenizados
16700/50000 archivos tokenizados
16800/50000 archivos tokenizados
16900/50000 archivos tokenizados
17000/50000 archivos tokenizados
17100/50000 archivos tokenizados
17200/50000 archivos tokenizados
17300/50000 archivos tokenizados
17400/50000 archivos tokenizados
17500/50000 archivos tokenizados
17600/50000 archivos tokenizados
17700/50000 archivos tokenizados
17800/50000 archivos tokenizados
17900/50000 archivos tokenizados
18000/50000 archivos tokenizados
18100/50000 archivos tokenizados
18200/50000 archivos tokenizados
18300/50000 archivos tokenizados
18400/50000 archivos tokenizados
18500/50000 archivos tokenizados
18600/50000 archivos tokenizados
18700/50000 archivos tokenizados
18800/50000 archivos tokenizados
18900/50000 archivos tokenizados
19000/50000 archivos tokenizados
19100/50000 archivos tokenizados
19200/50000 archivos tokenizados
19300/50000 archivos tokenizados
19400/50000 archivos tokenizados
19500/50000 archivos tokenizados
19600/50000 archivos tokenizados
19700/50000 archivos tokenizados
19800/50000 archivos tokenizados
19900/50000 archivos tokenizados
20000/50000 archivos tokenizados
20100/50000 archivos tokenizados
20200/50000 archivos tokenizados
20300/50000 archivos tokenizados
20400/50000 archivos tokenizados
20500/50000 archivos tokenizados
20600/50000 archivos tokenizados
20700/50000 archivos tokenizados
20800/50000 archivos tokenizados
20900/50000 archivos tokenizados
21000/50000 archivos tokenizados
21100/50000 archivos tokenizados
21200/50000 archivos tokenizados
21300/50000 archivos tokenizados
21400/50000 archivos tokenizados
21500/50000 archivos tokenizados
21600/50000 archivos tokenizados
21700/50000 archivos tokenizados
21800/50000 archivos tokenizados
21900/50000 archivos tokenizados
22000/50000 archivos tokenizados
22100/50000 archivos tokenizados
22200/50000 archivos tokenizados
22300/50000 archivos tokenizados
22400/50000 archivos tokenizados
22500/50000 archivos tokenizados
22600/50000 archivos tokenizados
22700/50000 archivos tokenizados
22800/50000 archivos tokenizados
22900/50000 archivos tokenizados
23000/50000 archivos tokenizados
23100/50000 archivos tokenizados
23200/50000 archivos tokenizados
23300/50000 archivos tokenizados
23400/50000 archivos tokenizados
23500/50000 archivos tokenizados
23600/50000 archivos tokenizados
23700/50000 archivos tokenizados
23800/50000 archivos tokenizados
23900/50000 archivos tokenizados
24000/50000 archivos tokenizados
24100/50000 archivos tokenizados
24200/50000 archivos tokenizados
24300/50000 archivos tokenizados
24400/50000 archivos tokenizados
24500/50000 archivos tokenizados
24600/50000 archivos tokenizados
24700/50000 archivos tokenizados
24800/50000 archivos tokenizados
24900/50000 archivos tokenizados
25000/50000 archivos tokenizados
25100/50000 archivos tokenizados
25200/50000 archivos tokenizados
25300/50000 archivos tokenizados
25400/50000 archivos tokenizados
25500/50000 archivos tokenizados
25600/50000 archivos tokenizados
25700/50000 archivos tokenizados
25800/50000 archivos tokenizados
25900/50000 archivos tokenizados
26000/50000 archivos tokenizados
26100/50000 archivos tokenizados
26200/50000 archivos tokenizados
26300/50000 archivos tokenizados
26400/50000 archivos tokenizados
26500/50000 archivos tokenizados
26600/50000 archivos tokenizados
26700/50000 archivos tokenizados
26800/50000 archivos tokenizados
26900/50000 archivos tokenizados
27000/50000 archivos tokenizados
27100/50000 archivos tokenizados
27200/50000 archivos tokenizados
27300/50000 archivos tokenizados
27400/50000 archivos tokenizados
27500/50000 archivos tokenizados
27600/50000 archivos tokenizados
27700/50000 archivos tokenizados
27800/50000 archivos tokenizados
27900/50000 archivos tokenizados
28000/50000 archivos tokenizados
28100/50000 archivos tokenizados
28200/50000 archivos tokenizados
28300/50000 archivos tokenizados
28400/50000 archivos tokenizados
28500/50000 archivos tokenizados
28600/50000 archivos tokenizados
28700/50000 archivos tokenizados
28800/50000 archivos tokenizados
28900/50000 archivos tokenizados
29000/50000 archivos tokenizados
29100/50000 archivos tokenizados
29200/50000 archivos tokenizados
29300/50000 archivos tokenizados
29400/50000 archivos tokenizados
29500/50000 archivos tokenizados
29600/50000 archivos tokenizados
29700/50000 archivos tokenizados
29800/50000 archivos tokenizados
29900/50000 archivos tokenizados
30000/50000 archivos tokenizados
30100/50000 archivos tokenizados
30200/50000 archivos tokenizados
30300/50000 archivos tokenizados
30400/50000 archivos tokenizados
30500/50000 archivos tokenizados
30600/50000 archivos tokenizados
30700/50000 archivos tokenizados
30800/50000 archivos tokenizados
30900/50000 archivos tokenizados
31000/50000 archivos tokenizados
31100/50000 archivos tokenizados
31200/50000 archivos tokenizados
31300/50000 archivos tokenizados
31400/50000 archivos tokenizados
31500/50000 archivos tokenizados
31600/50000 archivos tokenizados
31700/50000 archivos tokenizados
31800/50000 archivos tokenizados
31900/50000 archivos tokenizados
32000/50000 archivos tokenizados
32100/50000 archivos tokenizados
32200/50000 archivos tokenizados
32300/50000 archivos tokenizados
32400/50000 archivos tokenizados
32500/50000 archivos tokenizados
32600/50000 archivos tokenizados
32700/50000 archivos tokenizados
32800/50000 archivos tokenizados
32900/50000 archivos tokenizados
33000/50000 archivos tokenizados
33100/50000 archivos tokenizados
33200/50000 archivos tokenizados
33300/50000 archivos tokenizados
33400/50000 archivos tokenizados
33500/50000 archivos tokenizados
33600/50000 archivos tokenizados
33700/50000 archivos tokenizados
33800/50000 archivos tokenizados
33900/50000 archivos tokenizados
34000/50000 archivos tokenizados
34100/50000 archivos tokenizados
34200/50000 archivos tokenizados
34300/50000 archivos tokenizados
34400/50000 archivos tokenizados
34500/50000 archivos tokenizados
34600/50000 archivos tokenizados
34700/50000 archivos tokenizados
34800/50000 archivos tokenizados
34900/50000 archivos tokenizados
35000/50000 archivos tokenizados
35100/50000 archivos tokenizados
35200/50000 archivos tokenizados
35300/50000 archivos tokenizados
35400/50000 archivos tokenizados
35500/50000 archivos tokenizados
35600/50000 archivos tokenizados
35700/50000 archivos tokenizados
35800/50000 archivos tokenizados
35900/50000 archivos tokenizados
36000/50000 archivos tokenizados
36100/50000 archivos tokenizados
36200/50000 archivos tokenizados
36300/50000 archivos tokenizados
36400/50000 archivos tokenizados
36500/50000 archivos tokenizados
36600/50000 archivos tokenizados
36700/50000 archivos tokenizados
36800/50000 archivos tokenizados
36900/50000 archivos tokenizados
37000/50000 archivos tokenizados
37100/50000 archivos tokenizados
37200/50000 archivos tokenizados
37300/50000 archivos tokenizados
37400/50000 archivos tokenizados
37500/50000 archivos tokenizados
37600/50000 archivos tokenizados
37700/50000 archivos tokenizados
37800/50000 archivos tokenizados
37900/50000 archivos tokenizados
38000/50000 archivos tokenizados
38100/50000 archivos tokenizados
38200/50000 archivos tokenizados
38300/50000 archivos tokenizados
38400/50000 archivos tokenizados
38500/50000 archivos tokenizados
38600/50000 archivos tokenizados
38700/50000 archivos tokenizados
38800/50000 archivos tokenizados
38900/50000 archivos tokenizados
39000/50000 archivos tokenizados
39100/50000 archivos tokenizados
39200/50000 archivos tokenizados
39300/50000 archivos tokenizados
39400/50000 archivos tokenizados
39500/50000 archivos tokenizados
39600/50000 archivos tokenizados
39700/50000 archivos tokenizados
39800/50000 archivos tokenizados
39900/50000 archivos tokenizados
40000/50000 archivos tokenizados
40100/50000 archivos tokenizados
40200/50000 archivos tokenizados
40300/50000 archivos tokenizados
40400/50000 archivos tokenizados
40500/50000 archivos tokenizados
40600/50000 archivos tokenizados
40700/50000 archivos tokenizados
40800/50000 archivos tokenizados
40900/50000 archivos tokenizados
41000/50000 archivos tokenizados
41100/50000 archivos tokenizados
41200/50000 archivos tokenizados
41300/50000 archivos tokenizados
41400/50000 archivos tokenizados
41500/50000 archivos tokenizados
41600/50000 archivos tokenizados
41700/50000 archivos tokenizados
41800/50000 archivos tokenizados
41900/50000 archivos tokenizados
42000/50000 archivos tokenizados
42100/50000 archivos tokenizados
42200/50000 archivos tokenizados
42300/50000 archivos tokenizados
42400/50000 archivos tokenizados
42500/50000 archivos tokenizados
42600/50000 archivos tokenizados
42700/50000 archivos tokenizados
42800/50000 archivos tokenizados
42900/50000 archivos tokenizados
43000/50000 archivos tokenizados
43100/50000 archivos tokenizados
43200/50000 archivos tokenizados
43300/50000 archivos tokenizados
43400/50000 archivos tokenizados
43500/50000 archivos tokenizados
43600/50000 archivos tokenizados
43700/50000 archivos tokenizados
43800/50000 archivos tokenizados
43900/50000 archivos tokenizados
44000/50000 archivos tokenizados
44100/50000 archivos tokenizados
44200/50000 archivos tokenizados
44300/50000 archivos tokenizados
44400/50000 archivos tokenizados
44500/50000 archivos tokenizados
44600/50000 archivos tokenizados
44700/50000 archivos tokenizados
44800/50000 archivos tokenizados
44900/50000 archivos tokenizados
45000/50000 archivos tokenizados
45100/50000 archivos tokenizados
45200/50000 archivos tokenizados
45300/50000 archivos tokenizados
45400/50000 archivos tokenizados
45500/50000 archivos tokenizados
45600/50000 archivos tokenizados
45700/50000 archivos tokenizados
45800/50000 archivos tokenizados
45900/50000 archivos tokenizados
46000/50000 archivos tokenizados
46100/50000 archivos tokenizados
46200/50000 archivos tokenizados
46300/50000 archivos tokenizados
46400/50000 archivos tokenizados
46500/50000 archivos tokenizados
46600/50000 archivos tokenizados
46700/50000 archivos tokenizados
46800/50000 archivos tokenizados
46900/50000 archivos tokenizados
47000/50000 archivos tokenizados
47100/50000 archivos tokenizados
47200/50000 archivos tokenizados
47300/50000 archivos tokenizados
47400/50000 archivos tokenizados
47500/50000 archivos tokenizados
47600/50000 archivos tokenizados
47700/50000 archivos tokenizados
47800/50000 archivos tokenizados
47900/50000 archivos tokenizados
48000/50000 archivos tokenizados
48100/50000 archivos tokenizados
48200/50000 archivos tokenizados
48300/50000 archivos tokenizados
48400/50000 archivos tokenizados
48500/50000 archivos tokenizados
48600/50000 archivos tokenizados
48700/50000 archivos tokenizados
48800/50000 archivos tokenizados
48900/50000 archivos tokenizados
49000/50000 archivos tokenizados
49100/50000 archivos tokenizados
49200/50000 archivos tokenizados
49300/50000 archivos tokenizados
49400/50000 archivos tokenizados
49500/50000 archivos tokenizados
49600/50000 archivos tokenizados
49700/50000 archivos tokenizados
49800/50000 archivos tokenizados
49900/50000 archivos tokenizados
50000/50000 archivos tokenizados

In [ ]:
train_tokens

,chunk_id,token_ids,num_tokens,uid,pid
0,0,"[101, 1013, 1008, 1063, 1063, 1063, 1008, 1013...",512,415,27909
1,1,"[101, 21189, 12879, 3940, 1026, 20014, 1010, 2...",512,415,27909
2,2,"[101, 11675, 1059, 1006, 9530, 3367, 1056, 100...",512,415,27909
3,3,"[101, 1045, 1011, 1011, 1007, 1063, 16360, 100...",407,415,27909
4,0,"[101, 1013, 1008, 1063, 1063, 1063, 1008, 1013...",512,415,55938
...,...,...,...,...,...
95386,1,"[101, 8889, 8889, 8889, 8889, 8889, 2692, 1001...",507,276,3563
95387,0,"[101, 1001, 9375, 1035, 13675, 2102, 1035, 585...",512,276,75845
95388,1,"[101, 1011, 6694, 8889, 8889, 8889, 8889, 8889...",512,276,75845
95389,2,"[101, 1006, 1048, 2487, 1007, 1025, 16596, 100...",512,276,75845
95390,3,"[101, 2065, 1006, 2019, 2015, 1027, 1027, 1011...",35,276,75845

In [ ]:
train_tokens.to_csv("train_tokens.csv", index=False)

print(f"Guardado en: {output_path}")

Guardado en: /content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio/dataset/train_source.parquet

In [ ]:
dev_tokens = build_tokens_dataframe(dev_source)

100/25000 archivos tokenizados
200/25000 archivos tokenizados
300/25000 archivos tokenizados
400/25000 archivos tokenizados
500/25000 archivos tokenizados
600/25000 archivos tokenizados
700/25000 archivos tokenizados
800/25000 archivos tokenizados
900/25000 archivos tokenizados
1000/25000 archivos tokenizados
1100/25000 archivos tokenizados
1200/25000 archivos tokenizados
1300/25000 archivos tokenizados
1400/25000 archivos tokenizados
1500/25000 archivos tokenizados
1600/25000 archivos tokenizados
1700/25000 archivos tokenizados
1800/25000 archivos tokenizados
1900/25000 archivos tokenizados
2000/25000 archivos tokenizados
2100/25000 archivos tokenizados
2200/25000 archivos tokenizados
2300/25000 archivos tokenizados
2400/25000 archivos tokenizados
2500/25000 archivos tokenizados
2600/25000 archivos tokenizados
2700/25000 archivos tokenizados
2800/25000 archivos tokenizados
2900/25000 archivos tokenizados
3000/25000 archivos tokenizados
3100/25000 archivos tokenizados
3200/25000 archivos tokenizados
3300/25000 archivos tokenizados
3400/25000 archivos tokenizados
3500/25000 archivos tokenizados
3600/25000 archivos tokenizados
3700/25000 archivos tokenizados
3800/25000 archivos tokenizados
3900/25000 archivos tokenizados
4000/25000 archivos tokenizados
4100/25000 archivos tokenizados
4200/25000 archivos tokenizados
4300/25000 archivos tokenizados
4400/25000 archivos tokenizados
4500/25000 archivos tokenizados
4600/25000 archivos tokenizados
4700/25000 archivos tokenizados
4800/25000 archivos tokenizados
4900/25000 archivos tokenizados
5000/25000 archivos tokenizados
5100/25000 archivos tokenizados
5200/25000 archivos tokenizados
5300/25000 archivos tokenizados
5400/25000 archivos tokenizados
5500/25000 archivos tokenizados
5600/25000 archivos tokenizados
5700/25000 archivos tokenizados
5800/25000 archivos tokenizados
5900/25000 archivos tokenizados
6000/25000 archivos tokenizados
6100/25000 archivos tokenizados
6200/25000 archivos tokenizados
6300/25000 archivos tokenizados
6400/25000 archivos tokenizados
6500/25000 archivos tokenizados
6600/25000 archivos tokenizados
6700/25000 archivos tokenizados
6800/25000 archivos tokenizados
6900/25000 archivos tokenizados
7000/25000 archivos tokenizados
7100/25000 archivos tokenizados
7200/25000 archivos tokenizados
7300/25000 archivos tokenizados
7400/25000 archivos tokenizados
7500/25000 archivos tokenizados
7600/25000 archivos tokenizados
7700/25000 archivos tokenizados
7800/25000 archivos tokenizados
7900/25000 archivos tokenizados
8000/25000 archivos tokenizados
8100/25000 archivos tokenizados
8200/25000 archivos tokenizados
8300/25000 archivos tokenizados
8400/25000 archivos tokenizados
8500/25000 archivos tokenizados
8600/25000 archivos tokenizados
8700/25000 archivos tokenizados
8800/25000 archivos tokenizados
8900/25000 archivos tokenizados
9000/25000 archivos tokenizados
9100/25000 archivos tokenizados
9200/25000 archivos tokenizados
9300/25000 archivos tokenizados
9400/25000 archivos tokenizados
9500/25000 archivos tokenizados
9600/25000 archivos tokenizados
9700/25000 archivos tokenizados
9800/25000 archivos tokenizados
9900/25000 archivos tokenizados
10000/25000 archivos tokenizados
10100/25000 archivos tokenizados
10200/25000 archivos tokenizados
10300/25000 archivos tokenizados
10400/25000 archivos tokenizados
10500/25000 archivos tokenizados
10600/25000 archivos tokenizados
10700/25000 archivos tokenizados
10800/25000 archivos tokenizados
10900/25000 archivos tokenizados
11000/25000 archivos tokenizados
11100/25000 archivos tokenizados
11200/25000 archivos tokenizados
11300/25000 archivos tokenizados
11400/25000 archivos tokenizados
11500/25000 archivos tokenizados
11600/25000 archivos tokenizados
11700/25000 archivos tokenizados
11800/25000 archivos tokenizados
11900/25000 archivos tokenizados
12000/25000 archivos tokenizados
12100/25000 archivos tokenizados
12200/25000 archivos tokenizados
12300/25000 archivos tokenizados
12400/25000 archivos tokenizados
12500/25000 archivos tokenizados
12600/25000 archivos tokenizados
12700/25000 archivos tokenizados
12800/25000 archivos tokenizados
12900/25000 archivos tokenizados
13000/25000 archivos tokenizados
13100/25000 archivos tokenizados
13200/25000 archivos tokenizados
13300/25000 archivos tokenizados
13400/25000 archivos tokenizados
13500/25000 archivos tokenizados
13600/25000 archivos tokenizados
13700/25000 archivos tokenizados
13800/25000 archivos tokenizados
13900/25000 archivos tokenizados
14000/25000 archivos tokenizados
14100/25000 archivos tokenizados
14200/25000 archivos tokenizados
14300/25000 archivos tokenizados
14400/25000 archivos tokenizados
14500/25000 archivos tokenizados
14600/25000 archivos tokenizados
14700/25000 archivos tokenizados
14800/25000 archivos tokenizados
14900/25000 archivos tokenizados
15000/25000 archivos tokenizados
15100/25000 archivos tokenizados
15200/25000 archivos tokenizados
15300/25000 archivos tokenizados
15400/25000 archivos tokenizados
15500/25000 archivos tokenizados
15600/25000 archivos tokenizados
15700/25000 archivos tokenizados
15800/25000 archivos tokenizados
15900/25000 archivos tokenizados
16000/25000 archivos tokenizados
16100/25000 archivos tokenizados
16200/25000 archivos tokenizados
16300/25000 archivos tokenizados
16400/25000 archivos tokenizados
16500/25000 archivos tokenizados
16600/25000 archivos tokenizados
16700/25000 archivos tokenizados
16800/25000 archivos tokenizados
16900/25000 archivos tokenizados
17000/25000 archivos tokenizados
17100/25000 archivos tokenizados
17200/25000 archivos tokenizados
17300/25000 archivos tokenizados
17400/25000 archivos tokenizados
17500/25000 archivos tokenizados
17600/25000 archivos tokenizados
17700/25000 archivos tokenizados
17800/25000 archivos tokenizados
17900/25000 archivos tokenizados
18000/25000 archivos tokenizados
18100/25000 archivos tokenizados
18200/25000 archivos tokenizados
18300/25000 archivos tokenizados
18400/25000 archivos tokenizados
18500/25000 archivos tokenizados
18600/25000 archivos tokenizados
18700/25000 archivos tokenizados
18800/25000 archivos tokenizados
18900/25000 archivos tokenizados
19000/25000 archivos tokenizados
19100/25000 archivos tokenizados
19200/25000 archivos tokenizados
19300/25000 archivos tokenizados
19400/25000 archivos tokenizados
19500/25000 archivos tokenizados
19600/25000 archivos tokenizados
19700/25000 archivos tokenizados
19800/25000 archivos tokenizados
19900/25000 archivos tokenizados
20000/25000 archivos tokenizados
20100/25000 archivos tokenizados
20200/25000 archivos tokenizados
20300/25000 archivos tokenizados
20400/25000 archivos tokenizados
20500/25000 archivos tokenizados
20600/25000 archivos tokenizados
20700/25000 archivos tokenizados
20800/25000 archivos tokenizados
20900/25000 archivos tokenizados
21000/25000 archivos tokenizados
21100/25000 archivos tokenizados
21200/25000 archivos tokenizados
21300/25000 archivos tokenizados
21400/25000 archivos tokenizados
21500/25000 archivos tokenizados
21600/25000 archivos tokenizados
21700/25000 archivos tokenizados
21800/25000 archivos tokenizados
21900/25000 archivos tokenizados
22000/25000 archivos tokenizados
22100/25000 archivos tokenizados
22200/25000 archivos tokenizados
22300/25000 archivos tokenizados
22400/25000 archivos tokenizados
22500/25000 archivos tokenizados
22600/25000 archivos tokenizados
22700/25000 archivos tokenizados
22800/25000 archivos tokenizados
22900/25000 archivos tokenizados
23000/25000 archivos tokenizados
23100/25000 archivos tokenizados
23200/25000 archivos tokenizados
23300/25000 archivos tokenizados
23400/25000 archivos tokenizados
23500/25000 archivos tokenizados
23600/25000 archivos tokenizados
23700/25000 archivos tokenizados
23800/25000 archivos tokenizados
23900/25000 archivos tokenizados
24000/25000 archivos tokenizados
24100/25000 archivos tokenizados
24200/25000 archivos tokenizados
24300/25000 archivos tokenizados
24400/25000 archivos tokenizados
24500/25000 archivos tokenizados
24600/25000 archivos tokenizados
24700/25000 archivos tokenizados
24800/25000 archivos tokenizados
24900/25000 archivos tokenizados
25000/25000 archivos tokenizados

In [ ]:
dev_tokens

,chunk_id,token_ids,num_tokens,uid,pid
0,0,"[101, 1013, 1008, 1063, 1063, 1063, 1008, 1013...",512,415,12180
1,1,"[101, 1028, 1060, 1025, 1065, 11675, 1035, 105...",512,415,12180
2,2,"[101, 1007, 1063, 6140, 2546, 1006, 1000, 1001...",322,415,12180
3,0,"[101, 1013, 1008, 1063, 1063, 1063, 1008, 1013...",512,415,67901
4,1,"[101, 21189, 12879, 3940, 1026, 20014, 1010, 2...",512,415,67901
...,...,...,...,...,...
47349,1,"[101, 1011, 6694, 8889, 8889, 8889, 8889, 8889...",512,276,88752
47350,2,"[101, 1065, 2065, 1006, 999, 5210, 1007, 1063,...",210,276,88752
47351,0,"[101, 1001, 9375, 1035, 13675, 2102, 1035, 585...",512,276,81705
47352,1,"[101, 1045, 1033, 1012, 2117, 1027, 1045, 1025...",85,276,81705
47353,0,"[101, 1001, 2421, 1026, 16380, 25379, 1028, 10...",180,276,88570

In [ ]:
dev_tokens.to_csv("dev_tokens.csv", index=False)

print(f"Guardado en: {output_path}")

Guardado en: /content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio/dataset/train_source.parquet

In [ ]:
test_tokens = build_tokens_dataframe(test_source)

100/25000 archivos tokenizados
200/25000 archivos tokenizados
300/25000 archivos tokenizados
400/25000 archivos tokenizados
500/25000 archivos tokenizados
600/25000 archivos tokenizados
700/25000 archivos tokenizados
800/25000 archivos tokenizados
900/25000 archivos tokenizados
1000/25000 archivos tokenizados
1100/25000 archivos tokenizados
1200/25000 archivos tokenizados
1300/25000 archivos tokenizados
1400/25000 archivos tokenizados
1500/25000 archivos tokenizados
1600/25000 archivos tokenizados
1700/25000 archivos tokenizados
1800/25000 archivos tokenizados
1900/25000 archivos tokenizados
2000/25000 archivos tokenizados
2100/25000 archivos tokenizados
2200/25000 archivos tokenizados
2300/25000 archivos tokenizados
2400/25000 archivos tokenizados
2500/25000 archivos tokenizados
2600/25000 archivos tokenizados
2700/25000 archivos tokenizados
2800/25000 archivos tokenizados
2900/25000 archivos tokenizados
3000/25000 archivos tokenizados
3100/25000 archivos tokenizados
3200/25000 archivos tokenizados
3300/25000 archivos tokenizados
3400/25000 archivos tokenizados
3500/25000 archivos tokenizados
3600/25000 archivos tokenizados
3700/25000 archivos tokenizados
3800/25000 archivos tokenizados
3900/25000 archivos tokenizados
4000/25000 archivos tokenizados
4100/25000 archivos tokenizados
4200/25000 archivos tokenizados
4300/25000 archivos tokenizados
4400/25000 archivos tokenizados
4500/25000 archivos tokenizados
4600/25000 archivos tokenizados
4700/25000 archivos tokenizados
4800/25000 archivos tokenizados
4900/25000 archivos tokenizados
5000/25000 archivos tokenizados
5100/25000 archivos tokenizados
5200/25000 archivos tokenizados
5300/25000 archivos tokenizados
5400/25000 archivos tokenizados
5500/25000 archivos tokenizados
5600/25000 archivos tokenizados
5700/25000 archivos tokenizados
5800/25000 archivos tokenizados
5900/25000 archivos tokenizados
6000/25000 archivos tokenizados
6100/25000 archivos tokenizados
6200/25000 archivos tokenizados
6300/25000 archivos tokenizados
6400/25000 archivos tokenizados
6500/25000 archivos tokenizados
6600/25000 archivos tokenizados
6700/25000 archivos tokenizados
6800/25000 archivos tokenizados
6900/25000 archivos tokenizados
7000/25000 archivos tokenizados
7100/25000 archivos tokenizados
7200/25000 archivos tokenizados
7300/25000 archivos tokenizados
7400/25000 archivos tokenizados
7500/25000 archivos tokenizados
7600/25000 archivos tokenizados
7700/25000 archivos tokenizados
7800/25000 archivos tokenizados
7900/25000 archivos tokenizados
8000/25000 archivos tokenizados
8100/25000 archivos tokenizados
8200/25000 archivos tokenizados
8300/25000 archivos tokenizados
8400/25000 archivos tokenizados
8500/25000 archivos tokenizados
8600/25000 archivos tokenizados
8700/25000 archivos tokenizados
8800/25000 archivos tokenizados
8900/25000 archivos tokenizados
9000/25000 archivos tokenizados
9100/25000 archivos tokenizados
9200/25000 archivos tokenizados
9300/25000 archivos tokenizados
9400/25000 archivos tokenizados
9500/25000 archivos tokenizados
9600/25000 archivos tokenizados
9700/25000 archivos tokenizados
9800/25000 archivos tokenizados
9900/25000 archivos tokenizados
10000/25000 archivos tokenizados
10100/25000 archivos tokenizados
10200/25000 archivos tokenizados
10300/25000 archivos tokenizados
10400/25000 archivos tokenizados
10500/25000 archivos tokenizados
10600/25000 archivos tokenizados
10700/25000 archivos tokenizados
10800/25000 archivos tokenizados
10900/25000 archivos tokenizados
11000/25000 archivos tokenizados
11100/25000 archivos tokenizados
11200/25000 archivos tokenizados
11300/25000 archivos tokenizados
11400/25000 archivos tokenizados
11500/25000 archivos tokenizados
11600/25000 archivos tokenizados
11700/25000 archivos tokenizados
11800/25000 archivos tokenizados
11900/25000 archivos tokenizados
12000/25000 archivos tokenizados
12100/25000 archivos tokenizados
12200/25000 archivos tokenizados
12300/25000 archivos tokenizados
12400/25000 archivos tokenizados
12500/25000 archivos tokenizados
12600/25000 archivos tokenizados
12700/25000 archivos tokenizados
12800/25000 archivos tokenizados
12900/25000 archivos tokenizados
13000/25000 archivos tokenizados
13100/25000 archivos tokenizados
13200/25000 archivos tokenizados
13300/25000 archivos tokenizados
13400/25000 archivos tokenizados
13500/25000 archivos tokenizados
13600/25000 archivos tokenizados
13700/25000 archivos tokenizados
13800/25000 archivos tokenizados
13900/25000 archivos tokenizados
14000/25000 archivos tokenizados
14100/25000 archivos tokenizados
14200/25000 archivos tokenizados
14300/25000 archivos tokenizados
14400/25000 archivos tokenizados
14500/25000 archivos tokenizados
14600/25000 archivos tokenizados
14700/25000 archivos tokenizados
14800/25000 archivos tokenizados
14900/25000 archivos tokenizados
15000/25000 archivos tokenizados
15100/25000 archivos tokenizados
15200/25000 archivos tokenizados
15300/25000 archivos tokenizados
15400/25000 archivos tokenizados
15500/25000 archivos tokenizados
15600/25000 archivos tokenizados
15700/25000 archivos tokenizados
15800/25000 archivos tokenizados
15900/25000 archivos tokenizados
16000/25000 archivos tokenizados
16100/25000 archivos tokenizados
16200/25000 archivos tokenizados
16300/25000 archivos tokenizados
16400/25000 archivos tokenizados
16500/25000 archivos tokenizados
16600/25000 archivos tokenizados
16700/25000 archivos tokenizados
16800/25000 archivos tokenizados
16900/25000 archivos tokenizados
17000/25000 archivos tokenizados
17100/25000 archivos tokenizados
17200/25000 archivos tokenizados
17300/25000 archivos tokenizados
17400/25000 archivos tokenizados
17500/25000 archivos tokenizados
17600/25000 archivos tokenizados
17700/25000 archivos tokenizados
17800/25000 archivos tokenizados
17900/25000 archivos tokenizados
18000/25000 archivos tokenizados
18100/25000 archivos tokenizados
18200/25000 archivos tokenizados
18300/25000 archivos tokenizados
18400/25000 archivos tokenizados
18500/25000 archivos tokenizados
18600/25000 archivos tokenizados
18700/25000 archivos tokenizados
18800/25000 archivos tokenizados
18900/25000 archivos tokenizados
19000/25000 archivos tokenizados
19100/25000 archivos tokenizados
19200/25000 archivos tokenizados
19300/25000 archivos tokenizados
19400/25000 archivos tokenizados
19500/25000 archivos tokenizados
19600/25000 archivos tokenizados
19700/25000 archivos tokenizados
19800/25000 archivos tokenizados
19900/25000 archivos tokenizados
20000/25000 archivos tokenizados
20100/25000 archivos tokenizados
20200/25000 archivos tokenizados
20300/25000 archivos tokenizados
20400/25000 archivos tokenizados
20500/25000 archivos tokenizados
20600/25000 archivos tokenizados
20700/25000 archivos tokenizados
20800/25000 archivos tokenizados
20900/25000 archivos tokenizados
21000/25000 archivos tokenizados
21100/25000 archivos tokenizados
21200/25000 archivos tokenizados
21300/25000 archivos tokenizados
21400/25000 archivos tokenizados
21500/25000 archivos tokenizados
21600/25000 archivos tokenizados
21700/25000 archivos tokenizados
21800/25000 archivos tokenizados
21900/25000 archivos tokenizados
22000/25000 archivos tokenizados
22100/25000 archivos tokenizados
22200/25000 archivos tokenizados
22300/25000 archivos tokenizados
22400/25000 archivos tokenizados
22500/25000 archivos tokenizados
22600/25000 archivos tokenizados
22700/25000 archivos tokenizados
22800/25000 archivos tokenizados
22900/25000 archivos tokenizados
23000/25000 archivos tokenizados
23100/25000 archivos tokenizados
23200/25000 archivos tokenizados
23300/25000 archivos tokenizados
23400/25000 archivos tokenizados
23500/25000 archivos tokenizados
23600/25000 archivos tokenizados
23700/25000 archivos tokenizados
23800/25000 archivos tokenizados
23900/25000 archivos tokenizados
24000/25000 archivos tokenizados
24100/25000 archivos tokenizados
24200/25000 archivos tokenizados
24300/25000 archivos tokenizados
24400/25000 archivos tokenizados
24500/25000 archivos tokenizados
24600/25000 archivos tokenizados
24700/25000 archivos tokenizados
24800/25000 archivos tokenizados
24900/25000 archivos tokenizados
25000/25000 archivos tokenizados

In [ ]:
test_tokens

,chunk_id,token_ids,num_tokens,uid,pid
0,0,"[101, 1013, 1013, 1013, 2065, 1045, 2156, 2008...",285,NaN,34841
1,0,"[101, 1013, 1008, 7953, 1015, 1015, 1008, 1013...",512,NaN,68320
2,1,"[101, 1004, 12098, 2290, 2487, 1010, 12098, 56...",512,NaN,68320
3,2,"[101, 2522, 4904, 1026, 1026, 1015, 1026, 1026...",112,NaN,68320
4,0,"[101, 1001, 2421, 1026, 9896, 1028, 1001, 2421...",512,NaN,72734
...,...,...,...,...,...
47570,0,"[101, 1001, 2421, 1026, 9017, 1013, 2358, 1640...",87,NaN,62563
47571,0,"[101, 1001, 2421, 1026, 9017, 1013, 2358, 1640...",512,NaN,45920
47572,1,"[101, 1007, 1010, 25022, 2078, 1012, 5495, 100...",377,NaN,45920
47573,0,"[101, 1001, 2421, 1026, 9017, 1013, 2358, 1640...",192,NaN,81447
47574,0,"[101, 1013, 1013, 1013, 1013, 1013, 1013, 1013...",407,NaN,94031

In [ ]:
test_tokens.to_csv("test_tokens.csv", index=False)

print(f"Guardado en: {output_path}")

Guardado en: /content/drive/MyDrive/IA\ y\ Compiladores/Reto_plagio/dataset/train_source.parquet